/* Generated by cbindgen from crates/ffi. Do not edit by hand. */

#ifndef AUTOSUGGEST_H
#define AUTOSUGGEST_H

/* This file is auto-generated; regenerate via `cargo build -p autosuggest-ffi`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Handle one JSON request and return a newly allocated JSON response string.
 *
 * The returned pointer is owned by this library; free it with
 * [`autosuggest_string_free`]. Returns a valid error-response string for null
 * or non-UTF-8 input, and never returns null on the normal path.
 *
 * # Safety
 *
 * `request` must be either null or a valid pointer to a NUL-terminated C
 * string that stays valid for the duration of the call.
 */
char *autosuggest_request_json(const char *request);

/**
 * Free a string previously returned by [`autosuggest_request_json`].
 *
 * Passing null is a no-op. Passing any other pointer not produced by this
 * library, or freeing the same pointer twice, is undefined behavior.
 *
 * # Safety
 *
 * `s` must be either null or a pointer previously returned by
 * [`autosuggest_request_json`] and not yet freed.
 */
void autosuggest_string_free(char *s);

#endif  /* AUTOSUGGEST_H */
